### ISSUE TITLE
Error on accessing "Recent notes..."

### ISSUE THREAD

**Issue by pdanpdan** [aziz/PlainNotes#50]
```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 782, in run_
    return self.run()
  File "notes in C:\Users\H195849\AppData\Roaming\Sublime Text 3\Installed Packages\PlainNotes.sublime-package", line 97, in run
  File "notes in C:\Users\H195849\AppData\Roaming\Sublime Text 3\Installed Packages\PlainNotes.sublime-package", line 70, in setup_notes_list
AttributeError: 'module' object has no attribute 'return_sublist'
```

**Comment by pravic** [comment]
The same for me.

ST3 3141,

**Comment by pravic** [comment]
@aziz Any chance to update PlainNotes on [PackageControl.io](https://packagecontrol.io/packages/PlainNotes) to fix this issue?

**Comment by aziz** [comment]
Does not happen for me. I'll investigate it further. could you please share your settings as well? I mean PlainNotes settings

**Comment by pravic** [comment]
Sorry? This issue was fixed here on Feb 8, but PackageControl contains version 0.2.7 from Dec 03.

That's why I asked to update version there too.

**Comment by aziz** [comment]
Oh, sorry! I just tagged the most recent so it should be available on package control soon.

**Comment by pravic** [comment]
Thanks!
